### ISSUE TITLE
An issue with \textcolor{red}

### ISSUE THREAD

**Issue by gogo9th** [michal-h21/make4ht#174]
Hi,

I am recently facing one issue, suddenly.

I use `\textcolor{red}` a lot in my document, but for some reason, now the text using this coloring does not show in red anymore and show in black:

[https://fhetextbook.github.io/FHESchemeComparisonandSummary.html#fhe-scheme-comparison-and-summary](https://fhetextbook.github.io/FHESchemeComparisonandSummary.html#fhe-scheme-comparison-and-summary)

Do you see what the reason is by any chance? 
The source repository is this:

[https://github.com/fhetextbook/fhetextbook.github.io](https://github.com/fhetextbook/fhetextbook.github.io)

**Comment by michal-h21** [comment]
I think the same error happened in the past if there was a DOM error in parsing on that page, like:

```
[WARNING] domfilter: XML DOM parsing of refname.html failed:
[WARNING] domfilter: /home/michal/texmf/scripts/lua/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/mrow) [char=1986]

[DEBUG]   domfilter: Error context:
an><span
class="lmmi-10x-x-109">.</span><span
class="rm-lmtt-10x-x-109">org/wiki/Polynomial</span></mrow><mrow
><span
class="rm-lmr-8">r</span></mrow></msub
><span
class="rm-lmtt-10x-x-109">ing</
[DEBUG]   domfilter: Trying HTML DOM parsing
[WARNING] domfilter: HTML DOM parsing OK, DOM filters will be executed
```

But I cannot reproduce it with your document, so maybe it is something that was already fixed. I noticed another issue though - the bibliography has some MathML code instead of underscores, for example in a link to Wikipedia. This is caused by this line in your preamble:

```
\def\UrlBreaks{\do\/\do-}
```

It needs to contain `\do\_` too:

```
\def\UrlBreaks{\do\/\do-\do\_}
```

Or you can define it conditionally, only when TeX4ht is not loaded using:

```
\ifdefined\HCode\else
\def\UrlBreaks{\do\/\do-}
\fi
```

Another issue is in d01-thfe.tex:

```tex
$$
$\textsf{GSW}_{\vec{s}, \sigma}^{\beta, l}(m_2) = \Bigr \{ \{ \textsf{Lev}_{\vec{s}, \sigma}^{\beta, l} (-s_i \cdot m_2)  \}_{i=0}^{k-1}, \textsf{Lev}_{\vec{s}, \sigma}^{\beta, l}(m_2) \Bigl \} \in \mathbb{Z}_{q }^{(k+1) \cdot l \cdot (k+1)}$ \textcolor{red}{\# from \autoref{subsec:ggsw-enc}}

$$
```

The `\textcolor` and everything that follows is in the math mode, which results in errors too. I think you may want to remove the display math commands around this paragraph.

**Comment by gogo9th** [comment]
Thanks, I fixed `\def\UrlBreaks{\do\/\do-\do\_}`. 


Regarding `d01-tfhe.tex`, are you referring to this part:

```
$ $

$\textsf{GSW}_{\vec{s}, \sigma}^{\beta, l}(m_2) = \Bigr \{ \{ \textsf{Lev}_{\vec{s}, \sigma}^{\beta, l} (-s_i \cdot m_2)  \}_{i=0}^{k-1}, \textsf{Lev}_{\vec{s}, \sigma}^{\beta, l}(m_2) \Bigl \} \in \mathbb{Z}_{q }^{(k+1) \cdot l \cdot (k+1)}$ \textcolor{red}{\# from \autoref{subsec:ggsw-enc}}

$ $
```
Actually, this displays okay without any error on my machine when I visit the webpage [https://fhetextbook.github.io/HomomorphicCiphertexttoCiphertextMultiplication.html](https://fhetextbook.github.io/HomomorphicCiphertexttoCiphertextMultiplication.html), and the above code's `\textcolor{red}` is actually not in the math mode, but in the text mode. Your excerpt says `$$`, but the actual code I have is `$ $` [https://github.com/fhetextbook/fhetextbook.github.io/blob/ad156307f6c8492e43e1f889b7550fa57ac93acb/d01-tfhe.tex#L180C1-L180C4](https://github.com/fhetextbook/fhetextbook.github.io/blob/ad156307f6c8492e43e1f889b7550fa57ac93acb/d01-tfhe.tex#L180C1-L180C4). 

==================================

And I still get the math error when I visit
[https://fhetextbook.github.io/FHESchemeComparisonandSummary.html#fhe-scheme-comparison-and-summary](https://fhetextbook.github.io/FHESchemeComparisonandSummary.html#fhe-scheme-comparison-and-summary).

This is the code location where the error occurs: [https://github.com/fhetextbook/fhetextbook.github.io/blob/ad156307f6c8492e43e1f889b7550fa57ac93acb/d06-scheme-summary.tex#L142](https://github.com/fhetextbook/fhetextbook.github.io/blob/ad156307f6c8492e43e1f889b7550fa57ac93acb/d06-scheme-summary.tex#L142). When you tried to reproduce, does your line has the same code as this at this line?

**Comment by michal-h21** [comment]
> Regarding d01-tfhe.tex, are you referring to this part:

Yes, this it. It displays fine in the browser, but the HTML code contains wrong tags. If there are no other errors on the page caused by the DOM parsing errors, then it is not a problem. 

> This is the code location where the error occurs: https://github.com/fhetextbook/fhetextbook.github.io/blob/ad156307f6c8492e43e1f889b7550fa57ac93acb/d06-scheme-summary.tex#L142. When you tried to reproduce, does your line has the same code as this at this line?

I didn't have the same text, but after the update I have. It is still good after the compilation. Which exact command do you use for the compilation? Do you pass some additional TeX4ht options?

**Comment by michal-h21** [comment]
The Github Actions file looks fine, but the [run](https://github.com/fhetextbook/fhetextbook.github.io/actions/runs/16224278831/job/45812320779) looks weird:

```
[WARNING] domfilter: XML DOM parsing of FHESchemeComparisonandSummary.html failed:
[WARNING] domfilter: ...e/texdir/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/body) [char=337704]

[WARNING] domfilter: HTML DOM parsing OK, DOM filters will be executed
[WARNING] domfilter: XML DOM parsing of refname.html failed:
[WARNING] domfilter: ...e/texdir/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/section) [char=16113]

[WARNING] domfilter: HTML DOM parsing OK, DOM filters will be executed
[STATUS]  make4ht: Conversion finished
```

I am not sure why the DOM parsing failed on these two files. `refname.html` should be fixed by `\def\UrlBreaks{\do\/\do-\do\_}`, and `FHESchemeComparisonandSummary.html` doesn't fail on my system. Do you get the same errors when you compile the document on your computer?

**Comment by michal-h21** [comment]
I've also found an error in `b06-ggsw.tex`, there are swapped `\Bigl` and `\Bigr` commands, which leads to a DOM error and also wrong rendering. This is the correct version:

```tex
\begin{tcolorbox}[title={\textbf{\tboxlabel{\ref*{subsec:ggsw-enc}} GGSW Encryption}}]
$\textsf{GGSW}_{S, \sigma}^{\beta, l}(M) = \Bigl \{ \{ \textsf{GLev}_{S, \sigma}^{\beta, l}(-S_i \cdot M)  \}_{i=0}^{k-1}, \textsf{GLev}_{S, \sigma}^{\beta, l}(M) \Bigr \} \in \mathcal{R}_{\langle n, q \rangle }^{(k+1) \cdot l \cdot (k+1)}$
\end{tcolorbox}
```

**Comment by michal-h21** [comment]
Sure, MWE would be helpful, as it is quite large file. But first try to run it from your computer. It is possible that the issue is caused by the older version of TeX Live used in Github Actions.

**Comment by gogo9th** [comment]
I see, I just removed the `Make:match()` command:

[https://github.com/fhetextbook/fhetextbook.github.io/blob/b5351a30173109c99af54d4167d191d150b73765/.github/workflows/build.lua#L19](https://github.com/fhetextbook/fhetextbook.github.io/blob/b5351a30173109c99af54d4167d191d150b73765/.github/workflows/build.lua#L19)

However, the page seems to be still not working...
[https://fhetextbook.github.io/FHESchemeComparisonandSummary.html#fhe-scheme-comparison-and-summary](https://fhetextbook.github.io/FHESchemeComparisonandSummary.html#fhe-scheme-comparison-and-summary)
